In [26]:
import numpy as np
import pandas as pd

In [27]:
np.random.seed(0)
sale = np.random.randint(20, size=(5,3))
sale

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [28]:
weekly_sales = pd.DataFrame(sale,
                 index=['Mon', 'Tue', 'Wed', 'Thur', 'Fri'],
                 columns=['MacBook', 'Samsung', 'Dell'])
weekly_sales

MacBook  Samsung  Dell
Mon        12       15     0
Tue         3        3     7
Wed         9       19    18
Thur        4        6    12
Fri         1        6     7

In [29]:
# create the price array 
Prices = np.array([40,20,10])
Prices

array([40, 20, 10])

In [30]:
Laptop_prices = pd.DataFrame(Prices.reshape(1,3),
                              index=['Price'],
                              columns=['MacBook', 'Samsung', 'Dell'])
Laptop_prices

MacBook  Samsung  Dell
Price       40       20    10

In [31]:
Prices.shape

(3,)

In [32]:
total_sales = Prices.dot(sale.T)
total_sales

array([780, 250, 920, 400, 230])

In [33]:
total = pd.DataFrame(total_sales.reshape(1,5),
                           index=['Total ($)'])
total

0    1    2    3    4
Total ($)  780  250  920  400  230

In [34]:
Laptop_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [35]:
weekly_sales['Total ($)'] = total_sales.T
weekly_sales

MacBook  Samsung  Dell  Total ($)
Mon        12       15     0        780
Tue         3        3     7        250
Wed         9       19    18        920
Thur        4        6    12        400
Fri         1        6     7        230