In [1]:
import numpy as np


In [2]:
A = np.array([[3, 3, -1],
              [-2, -2, 1],
              [-4, -5, 2]])
A

array([[ 3,  3, -1],
       [-2, -2,  1],
       [-4, -5,  2]])

In [3]:
A.T

array([[ 3, -2, -4],
       [ 3, -2, -5],
       [-1,  1,  2]])

In [9]:
P = 1/2 *(A + A.T)
P

array([[ 3. ,  0.5, -2.5],
       [ 0.5, -2. , -2. ],
       [-2.5, -2. ,  2. ]])

In [8]:
P.T

array([[ 3. ,  0.5, -2.5],
       [ 0.5, -2. , -2. ],
       [-2.5, -2. ,  2. ]])

P is Symmetric Matrix

In [10]:
Q = 1/2 * (A - A.T)
Q

array([[ 0. ,  2.5,  1.5],
       [-2.5,  0. ,  3. ],
       [-1.5, -3. ,  0. ]])

In [11]:
Q.T

array([[ 0. , -2.5, -1.5],
       [ 2.5,  0. , -3. ],
       [ 1.5,  3. ,  0. ]])

In [12]:
Q.T * -1

array([[-0. ,  2.5,  1.5],
       [-2.5, -0. ,  3. ],
       [-1.5, -3. , -0. ]])

In [13]:
P + Q

array([[ 3.,  3., -1.],
       [-2., -2.,  1.],
       [-4., -5.,  2.]])

In [14]:
A

array([[ 3,  3, -1],
       [-2, -2,  1],
       [-4, -5,  2]])